### ISSUE TITLE
Rimworld Royality 1.1 undignified bedroom

### ISSUE THREAD

**Issue by ReisRyos** [fluffy-mods/StuffedFloors#23]
Use "golden metal plates" in bedroom and doesn't satisfy the requirments. Same in throneroom.

**Comment by InsanityPrelude** [comment]
Although it looks like it, this isn't really a bug I don't think.  (Verified on my end by the way.)  The trick is that in the base game Steel, Silver, and Gold plating are all distinct.  There's also only the one kind of metal flooring though.  Each type of flooring is either "FineFloor" or not "FineFloor" based on the type of flooring without respect to the material.  The "FineFloor" floor types which satisfy royal requirements can be made from anything, but they take twice as much work.

The issue here isn't that the royals are pissed off because their basic bitch solid gold flooring is cheap, they're pissed off because solid gold deck plating is tacky as hell and they want a fancy pattern in their floor.  They'd be happy with the much cheaper floor material so long as it wasn't just laid down in big solid plates.

I think the only way to solve this without a bunch of special cases or some weird calculation based on the value of the metal would be to separate them out into different "expensive" vs. "non-expensive" metals, but that defeats the whole point of making Stuffed Floors in the first place.

**Comment by InsanityPrelude** [comment]
Verified and fixed by bd026b34089eb13c49fcdb9f53b26504f2a38594.
